<a href="https://colab.research.google.com/github/blcktqq/python-spring/blob/main/practices/practice2/classwork/Practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np

# Створення пустих масивів NumPy з використанням функції empty()

In [ ]:
np.empty(5)

In [ ]:
## Створення матриці 3х4
np.empty((3,4))

# Створення непустих масивів NumPy

In [ ]:
np.array([1,2,3])

In [ ]:
# Заповненя нулями
a = np.zeros(5, dtype = int)
print(a)
print(a.dtype)

In [ ]:
a = np.zeros(5);
print(a)
print(a.dtype)

Генерація послідовностей

In [ ]:
np.arange(8)

In [ ]:
#Від 2 до 8 з кроком 3
np.arange(2,8,3)

Для послідовностей з плаваючою точкою:

In [ ]:
np.linspace(0, 2, 5)

# Заповнення масивів NumPy випадковими числами

In [ ]:
np.random.sample()

In [ ]:
np.random.randint(0,5)

# Звернення до елементів масивів

In [ ]:
a = np.array([1, 4, 5, 8])
a[2]

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
a[0:9:2]

Виборки

In [ ]:
# Всі елементи з `a` які менше 5
b = a[a<5]
print(b)

In [ ]:
# всі елементи масива a, що діляться націло на 2
b = a[a % 2 == 0]
print(b)

In [ ]:
# всі елементи масива a, які відповідають двум умовам одночасно (логічний вираз)
b = a[(a >2) & (a <= 8)]
print(b)

# Методи обробки одновимірних масивів Numpy

In [33]:
def describe(a):
  print(a)
  print(f"Форма  (shape) :{a.shape}")
  print(f"Кількість вимірів  (dimensions) :{a.ndim}")
  print(f"Розмір масиву: {a.size}")

In [ ]:
arr = np.full(shape = 4, fill_value=5)
describe(arr)

In [ ]:
arr = np.full(shape = (3,4), fill_value=5)
describe(arr)

In [ ]:
arr = np.full(shape = (2,3,4), fill_value=5)
describe(arr)

# Операції над масивами Numpy

In [42]:
a = np.random.randint(0,25,6)
print(a)
b = np.random.randint(0,5,6)
print(b)
c = a + b
print(c)

[ 9 13 22 22 22  1]
[1 0 3 0 0 1]
[10 13 25 22 22  2]


In [44]:

print(a)
#статистичні обчислення:
print(f"відхилення {np.std(a)}")
print(f"дисперсія {np.var(a)}")
print(f"середньоарифметичне {np.mean(a)}")

#визначення екстремальних значень масиву
print(f"Відхилення {np.std(a)}")

[ 9 13 22 22 22  1]
відхилення 7.987837977547838
дисперсія 63.80555555555554
середньоарифметичне 14.833333333333334
Відхилення 7.987837977547838
